In [3]:
import pandas as pd
import numpy as np

print(pd.__version__)

3.0.3

In [6]:
df = pd.read_csv(r"C:\Users\jaysr\OneDrive\Desktop\FoodConnect Analytics\data\food_wastage_data.csv")

In [7]:
df.head() #First 5 Rows

,Type of Food,Number of Guests,Event Type,Quantity of Food,Storage Conditions,Purchase History,Seasonality,Preparation Method,Geographical Location,Pricing,Wastage Food Amount
0,Meat,310,Corporate,450,Refrigerated,Regular,All Seasons,Buffet,Urban,Low,25
1,Meat,400,Birthday,500,Room Temperature,Regular,Winter,Buffet,Suburban,High,40
2,Vegetables,302,Birthday,371,Refrigerated,Regular,Summer,Buffet,Suburban,Low,27
3,Meat,491,Birthday,497,Refrigerated,Regular,All Seasons,Finger Food,Rural,High,32
4,Meat,300,Corporate,400,Refrigerated,Regular,Winter,Finger Food,Urban,Moderate,25

In [8]:
df.tail() #Last 5 Rows

,Type of Food,Number of Guests,Event Type,Quantity of Food,Storage Conditions,Purchase History,Seasonality,Preparation Method,Geographical Location,Pricing,Wastage Food Amount
1777,Baked Goods,310,Corporate,350,Room Temperature,Regular,Summer,Finger Food,Urban,High,35
1778,Baked Goods,284,Social Gathering,443,Room Temperature,Regular,Winter,Buffet,Rural,Low,32
1779,Fruits,220,Wedding,300,Room Temperature,Regular,All Seasons,Finger Food,Urban,Moderate,15
1780,Fruits,250,Wedding,350,Room Temperature,Regular,All Seasons,Finger Food,Rural,Moderate,20
1781,Baked Goods,400,Wedding,500,Room Temperature,Regular,Winter,Sit-down Dinner,Rural,High,45

In [9]:
df.shape #Dataset Shape

(1782, 11)

In [10]:
df.columns #Column Names

Index(['Type of Food', 'Number of Guests', 'Event Type', 'Quantity of Food',
       'Storage Conditions', 'Purchase History', 'Seasonality',
       'Preparation Method', 'Geographical Location', 'Pricing',
       'Wastage Food Amount'],
      dtype='str')

In [11]:
df.info() #Dataset Information

<class 'pandas.DataFrame'>
RangeIndex: 1782 entries, 0 to 1781
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Type of Food           1782 non-null   str
 1   Number of Guests       1782 non-null   int64
 2   Event Type             1782 non-null   str
 3   Quantity of Food       1782 non-null   int64
 4   Storage Conditions     1782 non-null   str
 5   Purchase History       1782 non-null   str
 6   Seasonality            1782 non-null   str
 7   Preparation Method     1782 non-null   str
 8   Geographical Location  1782 non-null   str
 9   Pricing                1782 non-null   str
 10  Wastage Food Amount    1782 non-null   int64
dtypes: int64(3), str(8)
memory usage: 153.3 KB

In [12]:
df.describe() #Summary Statistics

       Number of Guests  Quantity of Food  Wastage Food Amount
count       1782.000000       1782.000000          1782.000000
mean         317.804714        411.125701            28.536476
std           67.829658         65.204674            10.461317
min          207.000000        280.000000            10.000000
25%          267.000000        350.000000            20.000000
50%          302.000000        400.000000            26.500000
75%          350.000000        480.000000            35.000000
max          491.000000        500.000000            63.000000

In [15]:
df.dtypes #Data Types

Type of Food               str
Number of Guests         int64
Event Type                 str
Quantity of Food         int64
Storage Conditions         str
Purchase History           str
Seasonality                str
Preparation Method         str
Geographical Location      str
Pricing                    str
Wastage Food Amount      int64
dtype: object

In [16]:
df.nunique() #Unique Values

Type of Food              5
Number of Guests         39
Event Type                4
Quantity of Food         30
Storage Conditions        2
Purchase History          2
Seasonality               3
Preparation Method        3
Geographical Location     3
Pricing                   3
Wastage Food Amount      26
dtype: int64

In [18]:
df_clean = df.copy() #Make a Copy of the Dataset

In [19]:
df_clean.isnull().sum() #Check Missing Values

Type of Food             0
Number of Guests         0
Event Type               0
Quantity of Food         0
Storage Conditions       0
Purchase History         0
Seasonality              0
Preparation Method       0
Geographical Location    0
Pricing                  0
Wastage Food Amount      0
dtype: int64

In [20]:
df_clean.duplicated().sum() #Check Duplicate Rows

np.int64(164)

In [21]:
df_clean = df_clean.drop_duplicates() #Remove Duplicate Rows

In [ ]:
#Rename Columns

In [22]:
df_clean.columns = [
    'food_type',
    'number_of_guests',
    'event_type',
    'quantity_of_food',
    'storage_conditions',
    'purchase_history',
    'season',
    'preparation_method',
    'location',
    'pricing',
    'food_wastage_amount'
]

In [23]:
df_clean.columns

Index(['food_type', 'number_of_guests', 'event_type', 'quantity_of_food',
       'storage_conditions', 'purchase_history', 'season',
       'preparation_method', 'location', 'pricing', 'food_wastage_amount'],
      dtype='str')

In [24]:
df_clean.columns = df_clean.columns.str.strip() #Remove Extra Spaces

In [ ]:
##Standardize Text Columns

In [25]:
text_columns = [
    'food_type',
    'event_type',
    'storage_conditions',
    'purchase_history',
    'season',
    'preparation_method',
    'location',
    'pricing'
]

for col in text_columns:
    df_clean[col] = df_clean[col].str.strip().str.title()

In [26]:
df_clean.describe() #Check for Negative Values

       number_of_guests  quantity_of_food  food_wastage_amount
count       1618.000000       1618.000000          1618.000000
mean         318.380717        412.224969            28.628554
std           67.946519         64.714186            10.398187
min          207.000000        280.000000            10.000000
25%          267.750000        350.000000            20.000000
50%          302.000000        400.000000            27.000000
75%          362.750000        480.000000            35.000000
max          491.000000        500.000000            63.000000

In [53]:
df_clean.dtypes #Check Data Types

food_type                  str
number_of_guests         int64
event_type                 str
quantity_of_food         int64
storage_conditions         str
purchase_history           str
season                     str
preparation_method         str
location                   str
pricing                    str
food_wastage_amount      int64
food_consumed            int64
waste_percentage       float64
price_per_kg             int64
revenue_loss             int64
donation_possible          str
waste_category             str
event_size                 str
dtype: object

In [ ]:
#Save the Cleaned Dataset

In [28]:
df_clean.to_csv("food_waste_cleaned.csv", index=False)

In [30]:
#feature engineering#

In [ ]:
#Food Consumed

In [31]:
df_clean['food_consumed'] = df_clean['quantity_of_food'] - df_clean['food_wastage_amount']

In [32]:
df_clean.head()

,food_type,number_of_guests,event_type,quantity_of_food,storage_conditions,purchase_history,season,preparation_method,location,pricing,food_wastage_amount,food_consumed
0,Meat,310,Corporate,450,Refrigerated,Regular,All Seasons,Buffet,Urban,Low,25,425
1,Meat,400,Birthday,500,Room Temperature,Regular,Winter,Buffet,Suburban,High,40,460
2,Vegetables,302,Birthday,371,Refrigerated,Regular,Summer,Buffet,Suburban,Low,27,344
3,Meat,491,Birthday,497,Refrigerated,Regular,All Seasons,Finger Food,Rural,High,32,465
4,Meat,300,Corporate,400,Refrigerated,Regular,Winter,Finger Food,Urban,Moderate,25,375

In [ ]:
#Waste Percentage

In [33]:
df_clean['waste_percentage'] = (
    df_clean['food_wastage_amount'] /
    df_clean['quantity_of_food']
) * 100

In [34]:
df_clean['waste_percentage'] = df_clean['waste_percentage'].round(2)

In [35]:
#Price Mapping

In [36]:
price_map = {
    'Low': 120,
    'Moderate': 220,
    'High': 350
}

In [37]:
#Revenue Loss

In [38]:
df_clean['price_per_kg'] = df_clean['pricing'].map(price_map)

In [39]:
df_clean['revenue_loss'] = (
    df_clean['food_wastage_amount'] *
    df_clean['price_per_kg']
)

In [40]:
#Donation Possible

In [41]:
df_clean['donation_possible'] = np.where(
    df_clean['food_wastage_amount'] <= 30,
    'Yes',
    'No'
)

In [43]:
#Waste Category

In [44]:
def waste_level(x):
    if x < 20:
        return "Low"
    elif x < 35:
        return "Medium"
    else:
        return "High"

In [45]:
df_clean['waste_category'] = df_clean['food_wastage_amount'].apply(waste_level)

In [46]:
#Event Size

In [47]:
def event_size(x):
    if x < 250:
        return "Small"
    elif x < 400:
        return "Medium"
    else:
        return "Large"

In [48]:
df_clean['event_size'] = df_clean['number_of_guests'].apply(event_size)

In [49]:
#Save the Final Dataset

In [50]:
df_clean.to_csv("food_waste_final.csv", index=False)